### ISSUE TITLE
implement search provider

### ISSUE THREAD

**Issue by onny** [onny/nextcloud-app-radio#1]
Hey @ChristophWurst,
I wanted to implement a search provider on this app. Could you give me some hint?
Don't know where to put
```
OC.Plugins.register('OCA.Search', {
    attach: function(search) {
        search.setFilter('sms', mySearch);
    }
});
```
The searchbox doesn't appear in the upper right corner :(
I would appreciate any help, thanks :)

Best regards,
Jonas

**Comment by ChristophWurst** [comment]
Hi,

it should be sufficient to put that code somewhere here https://github.com/onny/nextcloud-app-radio/blob/1253c560f3e30a89388382971ecdbb7e76f45496/js/main.js#L116 so that it's invoked on page load.

> The searchbox doesn't appear in the upper right corner :(

It does only occur if a search plugin was registered. Otherwise it's hidden IIRC.

Let me know if that works :)

**Comment by onny** [comment]
Cool @ChristophWurst thanks for the support!
I tried it but the searchbox still doesn't appear: https://github.com/onny/nextcloud-app-radio/commit/be3953d06fba1ad5445359bc76da24bf4fa8bcc6#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR125

**Comment by ChristophWurst** [comment]
This patch seems to fix it:
```patch
diff --git a/js/main.js b/js/main.js
index 1a8a347..5c5f950 100644
--- a/js/main.js
+++ b/js/main.js
@@ -1,4 +1,4 @@
-$(window).on('load', function(){
+$(function(){
 
   $('body').on('click', 'tr', function() {
     var stationid = $(this).attr('data-id');
```

Apparently that means that the window load even is triggered a bit too late.

**Comment by onny** [comment]
Yeah, nice thank you!
