### ISSUE TITLE
[Feature Request] Sorting

### ISSUE THREAD

**Issue by BloodyIron** [onny/nextcloud-app-radio#10]
Can we get a way to sort channels? Say, by region of the world, listed category, bitrate, or content theme, etc.

**Comment by onny** [comment]
This is now implemented upstream and will be released soon. You'll find a category section there. Upstream: https://git.project-insanity.org/onny/nextcloud-app-radio

Best regards,
Jonas

**Comment by BloodyIron** [comment]
Woot!
