### ISSUE TITLE
Release 14 version

### ISSUE THREAD

**Issue by rullzer** [onny/nextcloud-app-radio#15]
Would it be possible for you to release a 14 version to the appstore?

**Comment by onny** [comment]
yep working on that. unfortunately I wasn't able to upload it to the appstore, see https://github.com/nextcloud/appstore/issues/570
but i'll try again, maybe i did something wrong ...

**Comment by rullzer** [comment]
Thnx!

Yes it ahs hiccups sometimes. But it should work now :)
