### ISSUE TITLE
Favorites sometimes not loading completly

### ISSUE THREAD

**Issue by weeman1337** [onny/nextcloud-app-radio#16]
Clicking the favorites displays some of the favorites, but not all.
I've to click some times to get the favorite I wanted.

When looking at the network request, it returned all the stations.
The problem may be in the frontend code.

Using Radio 0.6.2
With Nextcloud 14 RC2

**Comment by onny** [comment]
Hey weeman1337,
should be fixed now!

Regards,
Jonas

**Comment by weeman1337** [comment]
It now works - thanks.
