### ISSUE TITLE
Clean up "Broken radio station entry :( "

### ISSUE THREAD

**Issue by blackcrack** [onny/nextcloud-app-radio#19]
Hi, 

i have the actual Nextcloud with the actual Radion app,
a picture say more as 1000 words ..
best regards
Blacky

![screen 00000](https://user-images.githubusercontent.com/7925717/46525471-020a3480-c88c-11e8-8f95-e8d0ebebf29d.jpg) 
and this :+1: 
![screen 00001](https://user-images.githubusercontent.com/7925717/46525486-0b939c80-c88c-11e8-84a4-7f19a586f952.jpg)

**Comment by onny** [comment]
Hey, I also noticed this issue. I have to figure out how to fix this!

**Comment by blackcrack** [comment]
my work around was, use mysql-workbenech, search the entry of radioapp and remove the whole entry,
diasable the app in the admin, and reable it again for building up the radio-entry fresh,
so my think it is, you should check by user-id , as example something :  'UID = :userid1' 
and let check entry of the users by userbutton, and remove all wrong entry.. maybe something
(only because the user entry, nothing else : 
https://github.com/e-alfred/ocdownloader/pull/79/files/c60d7c0a7a3e59f641b9fba6bfc826169ea98780..3c4f8623eb597d7ad2aaabe64aa06df79ad8760a )

and let remove all wrong entrys .. by the user .. because i  guess it's a thing of the userdb/space .. or something.. in the XXXsql 

On/as the Admin could it maybe able to remove the whole entry, like i have done it and let reload and rebuild the entry in the DB , and this as admin .. for have a possible to clean fully it up .. as admin in the NC-Config under extra options..


the funny on it was, every where i have re open this Radioapp-Favorite page, become more and more entry where was wrong ! also je öfters aufrufen, mehr falsche Einträge .. it must be a bug like a cockroach,
works fine it's all okey, , but is one cockroach on the favorites, 
increases/multiplied she with each call as have give egg's of cockroach !
funny \*g*
 

best regards
Blacky

**Comment by onny** [comment]
Okay this is fixed in git. Not sure when I'll release a new version

**Comment by blackcrack** [comment]
@onny 

hey, very nice to give feedback !! how ever, in the future give some errors no more.. or something :)
what have you done,  add an "Cleanup" Button or so ? (this is what i whant only know.. Just curious, nose proof ![coriouse](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-1/ah.gif)

a big fad and wet Thss'ank You ! ![drrooooollll](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-1/drool.gif)

best regards
Blacky
