### ISSUE TITLE
Add custom radio stations

### ISSUE THREAD

**Issue by tomastd** [onny/nextcloud-app-radio#2]
Hi, great plugin!! I've just started using it and I like a lot.
Is it possible to add custom stations? 
How can we do that?
Thank you!

**Comment by onny** [comment]
The app uses Radio-Browser.info database as backend, look there if you want to add a station  :)

**Comment by tomastd** [comment]
Amazing!! Thank you!!!

Searching for them can be done directly from Nextcloud!! Great!! ;-)

Just another small question, is it possible to have some predefined stations defined by "admin"? 
I'm working for basque language user community. May it be as preselected category?

Thank you again.

**Comment by onny** [comment]
I'm glad you like the app :D
Hm that could be possible to implement. Maybe predefined favorites by the admin?

**Comment by tomastd** [comment]
It would be amazing, yes!!! ;-)

**Comment by GreekBoy-dev** [comment]
Hi, where is save this file ?
I have install Radio in the app menu of Nextcloud...
Nextcloud was installed by snap (in /var/snap/...)

**Comment by onny** [comment]
@gigidss see in ``/nextcloud/apps/radio``

**Comment by GreekBoy-dev** [comment]
Thanks you, I will see now, if I have a problem, i send you again an email

Envoyé de Mailspring (https://link.getmailspring.com/link/AD6D87C8-944C-48C1-BCD3-34899050EC48@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUpTV0dUU0tTRU9EUTZIUVc1UkZQNFYyM0cySUJFVkJOSEhBNVlDNzZRQHJlcGx5LmdpdGh1Yi5jb20%3D), la meilleure application de messagerie gratuite pour le travail

**Comment by GreekBoy-dev** [comment]
I have not a nextcloud folder in the root:

nextcloud@doussis-nextcloud:/$ ls
bin dev home initrd.img.old lib64 media opt root sbin srv sys usr vmlinuz
boot etc initrd.img lib lost+found mnt proc run snap swap.img tmp var vmlinuz.old

Envoyé de Mailspring (https://link.getmailspring.com/link/07FA817C-0FCE-487F-A1EB-C81839311F86@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUpTV0dUU0tTRU9EUTZIUVc1UkZQNFYyM0cySUJFVkJOSEhBNVlDNzZRQHJlcGx5LmdpdGh1Yi5jb20%3D), la meilleure application de messagerie gratuite pour le travail
