### ISSUE TITLE
Pause button shows always "II" sign

### ISSUE THREAD

**Issue by ghost** [onny/nextcloud-app-radio#4]
### Expected behavior
Sign changes between ">" and "II", when pressing the button.

### Actual behavior
Pause button shows always "II" sign

### Steps to reproduce the behavior
1. Open Radio App
2. Choose a radio station and click on it
3. Click on the play/pause button

### Additional Information
If I manually change the class of the play button via the web console `<button id="playbutton" class="pause"></button>` from "pause" to "play", it shows the ">" sign. If I click on it again, it changes back to "II", but it's not working vice versa.

### Environment
- **Radio version: 0.6.0
- **Browser vendor and version: Apple Safari v.11 / Google Chrome Version 61.0.3163.100 / Mozilla Firefox 56.0 (64-Bit)
- **Any browser plugins enabled? No 

#### Javascript
No logs

**Comment by onny** [comment]
Will be fixed in 0.6.2, thanks for reporting
