### ISSUE TITLE
nextcloud-app-TV

### ISSUE THREAD

**Issue by blackcrack** [onny/nextcloud-app-radio#5]
love this Radio app ! Thank you !

i have a idea : Nextcloud-app-TV

the same app, but with a 3th Frame where call the orginal pages with lifestream's
(autocheck Browsers Language) 
->
Land/Areas 's
(autoselect Language-Area/Land)

->
tv-channel's of the area/land (<href='' target='3thtvframe'>
with the original Homepages-url of the real orginal-livestreampage
(like in Germany/Austria/Swiss and so on (DE) http://www.phoenix.de/livestream/ )
for supporting the head/Homepage and Channel-Provider with klicks !
And let them see to be used. On ARD, the first Channel there in Germany it is 
a  combination of different Channels, but does not really support the Single Channel-provider
also the http://www.hr-fernsehen.de/livestream/index.html or the german ARTE 
https://www.arte.tv/de/live/ it is in the Mediatek from the ARD and support not the klicks
if we use alone because it summarizes all livestreams together on their Mediatek-Page
http://www.ardmediathek.de/tv/live what gives not one klick on the free Channel-provider
and therewith is the mediatek-common-chanells bad because no one goes to the real original 
Homepages of the Livestream-Channel-Provider, this can we support too. 
If we make 3 frames and do open/collecting the original homepage streaming page url 
from the TV-Channel-Provider.
All peoples can help with to collecting the orginal streaming page url's with the paches ;)

->
open in the 3th Frame(tv) with open one of the klicked Channels of the land/Area
and support therewith the Channelprovider of the channel with klicks.

therewith have we a Collecting like the Radio but we can 
looking Free TV Channels in our cloud if we have no Sat-Recvier or 
the Sat-reciver have a Bug because to much snow :)

and maybe it is not bad if t is there a possible for adding own urls
to add other pages at home, like pages who offers own program's
and be add there at own cloud like Sky or other Channels where 
you have a login and this pages adding and removing too by User.
Maybe making this possible wit a addon -configurations-text by user,
via popup-configurations dialog by user like by the audioplayer's mp3 configuring and so on ..

best regards
Blacky

**Comment by onny** [comment]
hey thanks for the idea.
i guess for tv streams we should create a new app since the backend database (radio-browser.info) only provides radio streams

best regards,
jonas

**Comment by blackcrack** [comment]
Hy @onny ,

You can writing on the TV-Chanels and can tell they are , they can make with to have 1. a good advertising, better klick's on the homepage and a possible to make a good TV-Stream Internet Streaming in the community for a really free TV-Community, because the direct linking and supports the Visit do the Homepage's because under or over the streaming-frame can be a Link to the homepage (target="_Blank").
Linking in TV-Browser at bottom or top of the TV-Stream app for the have TV-Chanel News ,
the next idea, TV-Browser can have a daughter as TV-Browserapp to have the possibility for an TV-Chanel News as Popup ;) for the Chanel where are Favourites and the channels where are listed ..

there a couples links : 

[ARD Livestream](http://mediathek.daserste.de/live)
[ONE Livestream](http://one.ard.de/tv/live)
[SR Livestream Saarland](http://www.sr.de/sr/fernsehen/livestream/)
[ZDF Livestream + Info/Neo](https://www.zdf.de/sender/zdf/zdf-live-beitrag-100.html)
[ZDF-NEO Livestream](https://www.zdf.de/sender/zdfneo/zdfneo-live-beitrag-100.html)
[Franken Fernsehen Livestream](https://www.frankenfernsehen.tv/livestream/)
[HR Livestream](http://www.hr-fernsehen.de/livestream/index.html)
[MDR Livestream](http://www.mdr.de/tv/index.html)
[MDR Livestream](https://www.mdr.de/mediathek/livestreams/mdr-plus/eventlivestreamzweiww-596.html)
[NDR Livestream](http://www.ndr.de/fernsehen/livestream/index.html)
[BR Livestream](https://www.br.de/mediathek/programmkalender/)
[RBB Livestream](http://mediathek.rbb-online.de/tv/live)
[RNF Livestream [Rhein-Neckar]](http://www.rnf.de/mediathek/video/rnf-livestream/)
[SR Livestream](https://www.sr.de/sr/fernsehen/livestream/index.html)
[SWR>> Livestream ](https://swrmediathek.de/content/live.htm)
[ServusTV Livestream](https://www.servus.com/de/tv/jetzt-bei-servus-tv/)
[WDR Livestream](http://www1.wdr.de/mediathek/video/live/index.html)
[NRWision Livestream](https://www.nrwision.de/programm/livestream.html)
[DRF1 Livestream [Deutschland Fernsehen]](http://drf-tv.de/drf/livestreams/livestream_drf1/Lifestream_drf1.de.jsp)
[Phoenix Livestream](http://www.phoenix.de/livestream/)
[3Sat Livestream](http://www.3sat.de/mediathek/?mode=play&obj=42667)
[Landesfernsehen Livestream](http://l-tv-live.de/)
[ARTE Livestream](https://www.arte.tv/de/direct/)
[Tele5 Livestream](http://www.tele5.de/live)
[Welt der Wunder Livestream](http://www.weltderwunder.de/videos/live)
[N24/Welt.de Livestream](https://www.welt.de/tv-programm-live-stream/)
[N24/Welt.de Doku Livestream (Must maybe directly write to tell they are are /ask, where the right link, or if they be in able to update the link.)](https://www.welt.de/tv-programm-n24-doku/)
[Tageschau.de Livestream](https://www.tagesschau.de/multimedia/livestreams/)
[Tageschau24 Livestream](https://programm.tagesschau24.de/Steuerseiten/Standalone-Videoplayer#)
[N-TV Livestream](http://www.n-tv.de/mediathek/livestream/)
[EuroNews Livestream](http://de.euronews.com/live)
[XITE Livestream](https://www.xite.tv/live)
[M TV Livestream](http://www.mtv.de/live)
[Deutsches Musik Fernsehen Livestream](https://www.deutsches-musik-fernsehen.de/)
[Sport1 Livestream](https://tv.sport1.de/sport1/)
[Nickelodeon Livestream](http://www.nick.de/live)
[Disney Channel Livestream](http://disneychannel.de/livestream)

don't work together with Zattoo and some pay-Channel's 
to hold it free.

the most Streaming pages works with https://videojs.com
for have a possible to scaling the Videostreams, therewith do you be in able for 
link in directly the Stream and can work with variables with the direct-stream link
via a variable-listing and therewith it is also possible to update in easy way
the link-listing : 
$_tvhomepage $_tvchanelname $_tvheading $_tvchanprog $_tvchanliveprog $_tvvideostream 
$_tvhomepageprogram $tvhompepagenews (maybe the news from the channel if they have a shouthbox or slidingnews or something at bottom frame in the TV-Channel-app where every 2-5 min reload the iframe "sandbox" https://www.w3schools.com/tags/tag_iframe.asp and other fine possibility's
Like, edit TV-Channel listing +add a TV-Chanel&Streamingurl to the Database + [send] send in the tv-channels to the community to add the new TV-Channels directly to the community's TV-Channel's Database where it is maybe on a free common Database or [some](https://github.com/PHP-Outburst/TextDB) ... :yum: 
this can make with

Don't forget a blacklisting TV-Channels where not able to send in on the common Database :wink: 
at home can the peoples make what they want and use what they want :godmode: to stay neutral ... :thought_balloon: ..

and because it is behind password saved space, it is private and internal linked in :grin:  
to speak also about open words in this closed theme/issue :relaxed: 
and international be different laws if i see in China and African and so on ;)

best regards
Blacky

**Comment by onny** [comment]
Hey Blacky,
nice writeup.
We can do such an app if there's a community database for tv streams with a good api.

Best regards,
Jonas

**Comment by blackcrack** [comment]
Hi @onny ,

the Database can you use via [textDB](https://github.com/PHP-Outburst/TextDB) in the appfolder if you can let work and can handle that (therewith it is the possible to update the community directly streaming links), well i be not a active php-programmer, i have only play around with [phpfilemirror](http://www.blackysgate.net/phpfilemirror/) and have give a bit help at the myUPB in the past , but i am at moment not in php-programming at moment, because i have the head full with other stuff from reallive .. but i know how could it works .. first should build up a addon and add the textdb for have a db where can be update
and then maybe make more about .. the communitydb can support an Provider later
or in the community have maybe later anyone who have running a server where 
it is possible to use it.. i guess ..

And a Community around Video TV Streaming links for this app is building up,
this can i bet with you, if you make a Forum and give a place for posting some videolinks,
i have found some forum in the past, but i have not save the links..
but i bet, this will speak around if this possible is give to add in a Own/NexTCloud -App
his own videourl to play the TV-URL's and have a possible to exchange TV-URL's from different TV-Channel's , with this it is also given many other """"free""" possibility's :wink: behind the Cloud

Onny, you're nice, thank you for this nice supporting \*vbs* :smile: :+1: 

best regards
Blacky
