### ISSUE TITLE
Can I use the app with Nextcloud 13?

### ISSUE THREAD

**Issue by elpraga** [onny/nextcloud-app-radio#6]
The last supported server version at the apps.nextcloud.com webpage is NC12.

I love the app, is it ready to be used with NC13? 

Thank you!

**Comment by onny** [comment]
Hi elpraga,
thanks for the feedback. I'll look into this and hope I don't have to change too much code to get it working with NC13.

Regards,
Jonas

**Comment by elpraga** [comment]
I've just tried simply changing `max-version` to `13` in the `info.xml`.  I'm able to choose and play stations in __Top__ category, but __Recent__, __Favorites__, and __Categories__ are not working.

Let me know if you need me to check something..

Thank you!

**Comment by elpraga** [comment]
Hello Jonas!

Did you have a chance to have a look at the changed you'd need to do to make it compatible with NextCloud 13?

**Comment by blackcrack** [comment]
Hi Onny, it's works pretty good,
i have only add ".app-radio #app-navigation > ul > li > a {color:white;}" for my theme
but so far, i have only change in the the versions number from 12 up to 13, more not.

best regards
Blacky

**Comment by elpraga** [comment]
Did you get the favourites working as well @blackcrack ?

**Comment by blackcrack** [comment]
take a look : http://www.blackysgate.de/files/folder-root/nextcloud/
and have fun with the theme.. the once or other should setting up, 
but so far should it works with the themes.
best regards
Blacky

**Comment by onny** [comment]
Thanks for the feedback, I uploaded a new version which should work now and also includes an anoying fix for loading the fav stations :)
