### ISSUE TITLE
Favorite list not always complete (multiple clicks needed)

### ISSUE THREAD

**Issue by efelon** [onny/nextcloud-app-radio#7]
Raspbian Stretch
Nextcloud 13
Nginx latest
PHP 7

After clicking on the link "favorites" in the sidebar the list sometimes shows not all favorites. I had to click it multiple times to see all. Which one it displays when not all are listed seams random to me.

Great, simple app, btw. :+1:

**Comment by onny** [comment]
thanks for reporting.
this is definitely an issue i'll going to fix

best regards,
jonas

**Comment by onny** [comment]
This issue is fixed in git master and will be available in version 0.6.3 :+1:
